# -*- mode: ruby -*-
# vi: set ft=ruby :

name = 'base'

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.hostname = 'insecure-server'
  config.vm.box = name

  config.vm.define config.vm.hostname

  config.vm.provider "vmware_fusion" do |vmware|
    vmware.gui = false
    vmware.vmx["memsize"] = 1024
    vmware.vmx["numvcpus"] = 1
  end

  config.vm.synced_folder "#{ENV['HOME']}", '/host-data'
  config.ssh.insert_key = false

  config.vm.provision "file", source: "run-stig-audit.sh", destination: "run-stig-audit.sh"
  config.vm.provision "shell", inline: "chmod a+x run-stig-audit.sh"

  config.vm.provision "shell" do |script|
    script.path = "add-vulnerabilities.sh"
  end
end
