# -*- mode: ruby -*-
# vi: set ft=ruby :

controller_name = 'ansible'
target_name = 'base'
num_servers = 2

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.provider 'vmware_fusion' do |vmware|
    vmware.gui = false
    vmware.vmx['memsize'] = 1024
    vmware.vmx['numvcpus'] = 1
  end

  config.vm.synced_folder "#{ENV['HOME']}", '/host-data'
  config.ssh.insert_key = false

  num_servers.times do |i|
    n = i + 1
    hostname = "#{target_name}-0#{n}"

    config.vm.define hostname do |node|
      node.vm.hostname = hostname
      node.vm.box = target_name
    end
  end

  config.vm.hostname = controller_name
  config.vm.box = controller_name

  config.vm.define controller_name do |node|
    node.vm.provision 'shell' do |script|
      script.path = 'set-ansible-hosts.sh'
      script.args = "-n #{num_servers}"
    end
  end
end
