# -*- mode: ruby -*-
# vi: set ft=ruby :

master = 'salt-master'
master_ip = '10.10.0.10'

minion = 'salt-minion'
minion_ip = '10.10.0.12'

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define master do |node|
    node.vm.hostname = master
    node.vm.box = master

    node.vm.provider "vmware_fusion" do |vmware|
      vmware.gui = false
      vmware.vmx["memsize"] = 1024
      vmware.vmx["numvcpus"] = 1
    end

    node.vm.synced_folder "#{ENV['HOME']}", '/host-data'
    node.ssh.insert_key = false
    node.vm.network "private_network", ip: master_ip

    node.vm.provision "shell" do |script|
      script.path = "set-master-interface.sh"
      script.args = "--ip #{master_ip}"
    end
  end

  config.vm.define minion do |node|
    node.vm.hostname = minion
    node.vm.box = minion

    node.vm.provider "vmware_fusion" do |vmware|
      vmware.gui = false
      vmware.vmx["memsize"] = 1024
      vmware.vmx["numvcpus"] = 1
    end

    node.vm.synced_folder "#{ENV['HOME']}", '/host-data'
    node.ssh.insert_key = false
    node.vm.network "private_network", ip: minion_ip

    node.vm.provision "shell" do |script|
      script.path = "set-minion-interface.sh"
      script.args = "--ip #{master_ip}"
    end
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
